---
name: Action Ansible Lint
description: Action to run Ansible lint.
author: L3D <l3d@c3woc.de>

inputs:
  target:
    description: |
      Target for ansible linter
      For example './', 'roles/my_role/' or 'site.yml'
    required: true
runs:
  using: docker
  image: Dockerfile
  env:
    TARGET: ${{ inputs.target }}
branding:
  icon: 'upload-cloud'
  color: 'black'
